#Cross-Origin Resource Sharing configuration
cors:
  allowOrigin: http://localhost:3000
  allowMethods: GET, POST, HEAD, PUT, DELETE
  contentType: application/json
  allowHeaders: origin, content-type, accept, x-requested-with
  maxAge: 3600