
#Cross-Origin Resource Sharing configuration
cors:
  allowOrigin: http://54.223.177.169:9000
  allowMethods: GET, POST, HEAD, PUT, DELETE
  contentType: application/json
  allowHeaders: origin, content-type, accept, x-requested-with
  maxAge: 3600
endpoints:
  shutdown:
    enabled: true